export const list = [
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
  {
    email: "basdnaksjdl@.com",
    name: "nvnsadkjnskvn",
    company: "hep",
    position: "CEO",
  },
];
